version: '3.8'

services:
  backend:
    build: ./backend
    container_name: fintrack_backend
    ports:
      - "5005:5005"
    environment:
      - DATABASE_URI=${DATABASE_URI}
      - FLASK_ENV=development
    depends_on:
      - db
    volumes:
      - ./backend:/app

  db:
    image: postgres:13
    container_name: fintrack_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
